/**
 * Settings Exporter — Generates and downloads a config.js file.
 * ARCcC: core/settings-panel/private/exporter/index.js
 *
 * This allows the user to persist settings in the GitHub Pages
 * repository by downloading and committing the generated file.
 */

const SettingsExporter = (() => {

  /**
   * Generate a config.js file from the given config object and trigger a download.
   * @param {SiteConfig} config
   */
  function exportAsJS(config) {
    const content = _buildFileContent(config);
    const blob    = new Blob([content], { type: 'text/javascript;charset=utf-8' });
    const url     = URL.createObjectURL(blob);

    const link    = document.createElement('a');
    link.href     = url;
    link.download = 'config.js';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  function _buildFileContent(config) {
    const json = JSON.stringify(config, null, 2);
    return `/**
 * config.js — Site configuration for Hideaki Bell Portfolio.
 * ARCcC: infrastructure/config/index.js
 *
 * Generated by the Settings Panel on ${new Date().toISOString().slice(0, 10)}.
 * To update: open the Settings Panel (Ctrl+Shift+P) and click "Export config.js",
 * then replace this file in your GitHub repository.
 *
 * IMPORTANT: After replacing this file, the DEFAULT_CONFIG object in
 * infrastructure/config/index.js will be overridden by this file's values.
 */

// Override DEFAULT_CONFIG with these saved settings
(function () {
  try {
    const SAVED_CONFIG = ${json};
    localStorage.setItem('hb_portfolio_config', JSON.stringify(SAVED_CONFIG));
  } catch (e) {
    console.warn('[config.js] Could not pre-load config:', e);
  }
})();
`;
  }

  return Object.freeze({ exportAsJS });
})();
